import hashlib  # IMPORTANDO A BIBLIOTECA PARA IMPLEMENTAR UMA INTERFACE COMUM PARA MUITOS ALGORITMOS DE HASH

# A VARIÁVEL RECEBE O HASH GERADO DA STRING INFORMADA
resultado = hashlib.sha256(b"Python Security")

# IMPRIME O HASH GERADO
print(f"HASH DA STRING: {resultado.hexdigest()}")
